networks:
  default:

volumes:
  images:
  logs:
  image_hosting_database:

services:
  app:
    container_name: app
    env_file:
      - ./.env
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./images:/images
      - ./logs:/var/log/nginx
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - app

  db:
    container_name: db_ih
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - image_hosting_database:/var/lib/postgres/data
    networks:
      - default
    restart: always